fnd/__init__.py
from flask import Flask, g
import sqlite3
from .data import twitter
import botometer
import json

DATABASE = '../scraper/fn-detect.db'

def get_db():
    db = getattr(g, '_database', None)
    if db is None:
        db = g._database = sqlite3.connect(DATABASE)
    return db

def get_twitter():
    tapi = getattr(g, '_twitter', None)
    if tapi is None:
        tapi = g._twitter = twitter.create_twitter('twitter_config.json')
    return tapi

def get_bom():
    bom = getattr(g, '_bom', None)
    if bom is None:
        bom = g.bom = botometer.Botometer(
            mashape_key=json.load(open('mashape.json', 'r'))['mashape'],
            **json.load(open('twitter_config.json', 'r')))
    return bom

def create_app(debug=True):
    app = Flask(__name__)
    app.debug = debug

    # blueprints!
    from fnd.main import main_blueprint
    app.register_blueprint(main_blueprint)

    @app.teardown_appcontext
    def close_db_conn(exception):
        db = getattr(g, '_database', None)
        if db is not None:
            db.close()

    return app

fnd/data/__init__.py
# your code here

fnd/main/__init__.py
from flask import Blueprint
from jinja2 import TemplateNotFound

main_blueprint = Blueprint('main_blueprint', __name__, template_folder='../templates/')

from . import routes

fnd/main/routes.py
from flask import render_template, request, jsonify
from .. import get_twitter, get_bom
from jinja2 import TemplateNotFound
from . import main_blueprint
from ..data import twitter
import arrow
import json
import math

@main_blueprint.route('/')
def index():
    return render_template('index.html')

@main_blueprint.route('/dox/start')
def doxstart():
    return render_template('doxstart.html')

@main_blueprint.route('/dox/load/<uname>')
def load_dox(uname):
    return render_template('loading.html', username=uname)

@main_blueprint.route('/dox/username/<uname>', methods=['POST', 'GET'])
def dox_user(uname):
    if request.method == 'POST':
        username = request.form['username']
    else:
        username = uname
    if username[0] == '@':
        username = username[1:]

    api = get_twitter()
    user = twitter.get_user(api, username)
    tweets = twitter.get_tweets(api, username, batches=3, exclude_replies=True)
    print('{} tweets scanned'.format(len(tweets)))
    graphs = twitter.analyze_tweets(tweets)
    days_old = (arrow.utcnow() - twitter.get_created_at(user)).days
    sample = {
        'size': len(tweets),
        'oldest': twitter.get_created_at(tweets[-1]).humanize(),
        'tweets_per_day': math.floor(user.statuses_count / days_old),
        'days_old': days_old
    }

    bom = get_bom()
    results = bom.check_account(username)
    print(results)

    def grade(num):
        if num > 0.66:
            return 'is-danger'
        elif num > 0.33:
            return 'is-warning'
        return 'is-success'

    def interpret(num):
        if num > 0.66:
            return 'probably a bot'
        elif num > 0.33:
            return 'may be a bot'
        return 'probably not a bot'

    return render_template('doxshow.html', username=username, user=user, bom=results, graphs=graphs, grade=grade, interpreted_score=interpret(results['scores']['english']), sample=sample)


@main_blueprint.route('/api/dox/<username>')
def api_dox(username):
    bom = get_bom()
    results = bom.check_account(username)
    return jsonify(results)

fnd/templates/base.html
<html>
	<head>
		<title>{% block title %}page{% endblock %} - fn-detect</title>

		{% block js_head %}{% endblock %}
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='index.css') }}">
		{# <script src="{{ url_for('static', filename='semantic.js') }}"></script> #}
		{% block css %}{% endblock %}
	</head>
	<body>
		{% block body %}{% endblock %}
		{% block js %}{% endblock %}
	</body>
</html>

fnd/templates/doxshow.html
{% extends "page.html" %}

{% block title %}{{ username }}{% endblock %}

{% block content %}

<h1>Overview for @{{username}}</h1>
<hr>

<div class="images">
	<div class="banner">
		<img src="{{ user.profile_banner_url }}">
	</div>
	<img class="profile" src="{{ user.profile_image_url }}">
	
</div>

<h3 class="is-size-3">Bot scan results:</h3>
<div class="progressbars">
	<b class="is-size-4"> Overall: {{(bom['scores']['english'] * 100)|round|int}}% - {{ interpreted_score }}</b>
	<progress class="progress is-large {{ grade(bom['scores']['english']) }}" value="{{ (bom['scores']['english'] * 100)|round }}" max="100"></progress>
	<b>Universal (language independent score): {{ (bom['scores']['universal'] * 100)|round|int }}%</b>	
	<progress class="progress is-medium {{ grade(bom['scores']['universal']) }}" value="{{ (bom['scores']['universal'] * 100)|round }}" max="100"></progress>

	{% for key in bom['categories'] %}
	<b class="capitalize">{{ key }}: {{ (bom['categories'][key] * 100)|round|int }}%</b>
	<progress class="progress {{ grade(bom['categories'][key]) }}" value="{{ bom['categories'][key] * 100 }}" max="100"></progress>

	{% endfor %}
</div>

{# The Wrong Way To Do It (tm) #}
<h3 class="is-size-3">Tweet Heatmap (UTC):</h3>
<div class="heatmap">
	<div class="heatmap-row">
		<div class="heatmap-label">&nbsp;</div>
		<div class="heatmap-scale">
			{% for i in range(0, 24) %}
			<span class="tick" style="margin-left: {{ i / 0.24 }}%">{{ i }}</span>
			{% endfor %}
		</div>
	</div>
	{% for key in graphs['timemap'] %}
	<div class="heatmap-row">
		<div class="heatmap-label">{{ key }}</div>
		<div class="heatmap-area">
			{% for num in graphs['timemap'][key] %}
				<span class="tick" style="margin-left: {{num / 864.0}}%"></span>
			{% endfor %}
		</div>
	</div>
	{% endfor %}
	<i>{{ sample['size'] }} tweets sampled, oldest {{ sample['oldest'] }}</i>
</div>
<br>

<h3 class="is-size-3">Extracted Twitter parameters</h3>
<table>
	<thead>
		<tr>
			<th>Field</th>
			<th>Value</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Name</td>
			<td>{{ user.name }}</td>
		</tr>
		<tr>
			<td>Screen Name</td>
			<td><a href="https://twitter.com/{{ user.screen_name }}" rel="noopener" target="_blank">@{{ user.screen_name }}</a></td>
		</tr>
		<tr>
			<td>Description</td>
			<td>{{ user.description }}</td>
		</tr>
		<tr>
			<td>Location</td>
			<td>{{ user.location }}</td>
		</tr>
		<tr>
			<td>Verified?</td>
			<td>{{ user.verified }}</td>
		</tr>
		<tr>
			<td>Joined</td>
			<td>{{ user.created_at }} ({{ sample['days_old']}} days ago)</td>
		</tr>
		<tr>
			<td>Tweets</td>
			<td>{{ user.statuses_count }} ({{ sample['tweets_per_day'] }} per day)</td>
		</tr>
		<tr>
			<td>Language</td>
			<td>{{ user.lang }}</td>
		</tr>
		<tr>
			<td>Twitter ID</td>
			<td>{{ user.id_str }}</td>
		</tr>
		<tr>
			<td>Followers</td>
			<td>{{ user.followers_count }}</td>
		</tr>
		<tr>
			<td>Timezone</td>
			<td>{{ user.time_zone }}</td>
		</tr>
		<tr>
			<td>User Link</td>
			<td><a href="{{ user.url }}" rel="noopener" target="_blank">{{ user.url }}</a></td>
		</tr>
		<tr>
			<td>Favorites</td>
			<td>{{ user.favourites_count }}</td>
		</tr>
	</tbody>
</table>
<br>


{% endblock %}
{% block js %}
<script src="{{ url_for('static', filename='lib/d3.v4.min.js') }}"></script>
<script type="text/plain" id="graphs">{{ graphs|safe }}</script>
{% endblock %}

fnd/templates/doxstart.html
{% extends "page.html" %}

{% block title %}dox{% endblock %}

{% block content %}
<h1> Deep scan Twitter user </h1>
<hr>
<form id="dox">
		<div class="form-group">
			<label for="username">Username to scan</label>
			<input name="username" class="dox-username" type="text" placeholder="@realDonaldTrump" autocomplete="off"/>
		</div>
</form>
{% endblock %}

{% block js %}
<script type="text/javascript">
window.onload = () => {
	document.querySelector('#dox').addEventListener('submit', redirectToScan)
}
const redirectToScan = e => {
	e.preventDefault()
	let val = document.querySelector('input[name="username"]').value
	console.log(val)
	window.location.pathname = `/dox/load/${val}`
	return false
}
</script>
{% endblock %}

fnd/templates/index.html
{% extends "page.html" %}

{% block title %}landing{% endblock %}

{% block content %}
<h1>Content</h1>
<hr/>
<p> foo bar baz </p>
{% endblock %}

fnd/templates/loading.html
<html>
	<head>
		<title>loading...</title>
		<meta http-equiv="refresh" content="0; url=/dox/username/{{ username }}" >
	</head>
	<body>
		<div class="container">
			<div class="preload-outer">
			</div>
			<div class="preload-inner">
			</div>
		</div>
		<style>
			body {
				margin: 0;
				padding: 0;
				border: 0;
			}

			.preload-outer {
				position: absolute;
				top: calc(50vh - 40px);
				left: calc(50vw - 40px);
				width: 80px;
				height: 80px;
				transform-origin: 50% 50%;
				animation-name: rotatePreloader;
				animation-duration: 0.5s;
				animation-iteration-count: infinite;
				animation-timing-function: linear;
				margin: 0;
				padding: 0;
				border: 2px solid black;
				border-radius: 50%;
				border-bottom-color: rgba(0, 0, 0, 0);
				border-left-color: rgba(0, 0, 0, 0);
			}

			.preload-inner {
				position: absolute;
				top: calc(50vh - 30px);
				left: calc(50vw - 30px);
				width: 60px;
				height: 60px;
				transform-origin: 50% 50%;
				animation-name: rotatePreloader;
				animation-duration: 0.5s;
				animation-iteration-count: infinite;
				animation-timing-function: linear;
				margin: 0;
				padding: 0;
				border: 2px solid black;
				border-radius: 50%;
				border-top-color: rgba(0, 0, 0, 0);
				border-right-color: rgba(0, 0, 0, 0);
				animation-direction: reverse;
			}

			@keyframes rotatePreloader {
				0% {
					transform: rotate(0deg);
				}
				50% {
					transform: rotate(180deg);
				}
				100% {
					transform: rotate(360deg);
				}
			}

		</style>
	</body>
</html>

fnd/templates/page.html
{% extends "base.html" %}

{% block body %}
<div class="page">
	<div class="sidebar">
		<div class="top">
			<div class="title">fn-detect</div>
			<div class="subtitle">htb 2018</div>
		</div>
		<ul class="navigation">
			<li><a href="{{ url_for('main_blueprint.index') }}">main</a></li>
			<li><a href="#">articles</a></li>
			<li><a href="{{ url_for('main_blueprint.doxstart') }}">scan user</a></li>
			<li><a href="#">scan article</a></li>
		</ul>
	</div>
	<div class="content">
		<div class="inner-content">
			{% block content %}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}